# Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

INHERIT: ../base.yml

# Project information
site_name: &site_name Identity Server
site_description: Identity Server
site_url: https://wso2.com/is/docs

# Configuration
theme:
  custom_dir: ../theme/material
  logo: assets/images/identity-server-docs-logo-dark.svg
  logo_light: assets/images/identity-server-docs-logo.svg
  favicon: assets/images/identity-server-favicon.png

extra:
  base_path: /is/docs/
  product: IS
  product_name: Identity Server
  # nav_list:
  #   - Get Started
  #   - Guides
  #   - Tutorials
  #   - Integrations
  #   - APIs
  #   - References
  home_page_cards:
    - section:
      - title: Migration Search
        icon: .icons/material/magnify.svg
        icon_color: icon-color-1
        list_items:
          - title: Create your Asgardeo account
            url: Get Started|Create your Asgardeo account
          - title: Try login with Asgardeo
            url: Get Started|Try login with Asgardeo

watch:
  - ../theme/material
  - ../base.yml

plugins:
  - search
  - markdownextradata: {}
  - include-markdown
  - redirects:
      redirect_maps:
        # 'references/grant-types-in-asgardeo.md': 'references/grant-types.md'
        # 'guides/users/manage-collaborators.md': 'guides/users/manage-administrators.md'
        # 'guides/users/manage-customers.md': 'guides/users/manage-users.md'
        # 'guides/user-self-service/register-security-key.md': 'guides/user-self-service/register-passkey.md'
        # 'guides/authentication/enterprise-login/index.md': 'guides/authentication/standard-based-login/index.md'
        # 'guides/authentication/enterprise-login/add-oidc-idp-login.md': 'guides/authentication/standard-based-login/add-oidc-idp-login.md'
        # 'guides/authentication/enterprise-login/add-saml-idp-login.md': 'guides/authentication/standard-based-login/add-saml-idp-login.md'
        # 'guides/asgardeo-events.md': 'guides/monitoring/asgardeo-events.md'
        # 'guides/user-self-service/customer-self-service-portal.md': 'guides/user-self-service/configure-self-service-portal.md'
        # 'guides/authentication/conditional-auth/ai-loginflow.md': 'guides/authentication/ai-loginflow.md'
        # 'guides/user-accounts/configure-self-service-portal.md': 'guides/user-self-service/configure-self-service-portal.md'
        # 'guides/organization-management/onboard-sub-org-admins.md': 'guides/organization-management/onboard-org-admins.md'
        # 'guides/authentication/configure-a-trusted-token-issuer.md': 'guides/authentication/configure-token-exchange.md'
        # 'guides/applications/manage-application-roles.md': 'guides/users/manage-roles.md'
        # 'guides/authentication/app-native-authentication/configure-advanced-app-native-settings.md': 'guides/authentication/app-native-authentication/index.md'
        # 'apis/authentication.md': 'apis/index.md'
        './apim-revamped/migration-catalog/upgrading-to-apim-420/index.md': 'apims/index.md'



# Navigation
nav:
  - Home:
    - Home: index.md
  # - Get Started:
  #   - Get Started - Overview: get-started/index.md
  #   - Create your Asgardeo account: get-started/create-asgardeo-account.md
  #   - Try login with Asgardeo: get-started/try-it-application.md
  #   - Start integrating Asgardeo into apps:
  #     - Start integrating Asgardeo into apps: get-started/start-integrating-apps/index.md
  #     - Try for a sample app:
  #       - Try for a sample app: get-started/try-samples/index.md
  #       - Single Page apps:
  #         - React: get-started/try-samples/qsg-spa-react.md
  #         - JavaScript: get-started/try-samples/qsg-spa-javascript.md
  #       - Web apps:
  #         - OIDC Java EE: get-started/try-samples/qsg-oidc-webapp-java-ee.md
  #         - SAML Java EE: get-started/try-samples/qsg-saml-webapp-java-ee.md
  #     - Try for your own app:
  #       - Try for your own app: get-started/try-your-own-app/index.md
  #       - Single Page apps:
  #         - React: get-started/try-your-own-app/react.md
  #         - Javascript: get-started/try-your-own-app/javascript.md
  #       - Web apps:
  #         - OIDC Java EE: get-started/try-your-own-app/java-ee-oidc.md
  #         - SAML Java EE: get-started/try-your-own-app/java-ee-saml.md


  # - API Migration:
  #     - Nav Doc - Overview: ./apim-revamped/migration-catalog/upgrading-to-apim-420/index.md
  #     - Api M Migration Guidelines: ./apim-revamped/general-guidelines.md
  #     - changed between the API-M versions:
  #         - What has Changed: ./apim-revamped/what-has-changed.md
  #         - About this release: https://apim.docs.wso2.com/en/4.2.0/get-started/about-this-release/
  #     - Update latest update level: https://apim.docs.wso2.com/en/4.2.0/administer/updating-wso2-api-manager/#wso2-updates-20

  #     - Upgrading from API-M 4.1.0 to 4.2.0: ./apim-revamped/migration-catalog/upgrading-to-apim-420/upgrading-from-410-to-420/config-migration/
# C:\Users\Kavindu\Documents\MkDocs\New New docs-is main\docs-is\en\migration\docs\api-manager\apim-revamped\migration-catalog\upgrading-to-apim-400\upgrading-from-300-to-400\upgrading-from-300-to-400.md

  - Documentation: 
    - What has changed:
      - 5.2.0 to 5.7.0: 
        - 5.2.0 to 5.3.0: identity-server/migration-docs/what-has-changed/config-changes-5.2.0-5.3.0.md
        - 5.3.0 to 5.4.0: identity-server/migration-docs/what-has-changed/config-changes-5.3.0-5.4.0.md
        - 5.4.0 to 5.5.0: identity-server/migration-docs/what-has-changed/config-changes-5.4.0-5.5.0.md
        - 5.5.0 to 5.6.0: identity-server/migration-docs/what-has-changed/config-changes-5.5.0-5.6.0.md
        - 5.6.0 to 5.7.0: identity-server/migration-docs/what-has-changed/config-changes-5.6.0-5.7.0.md

      - 5.7.0 to 5.8.0: identity-server/migration-docs/what-has-changed/what-has-changes-5.7.0 to 5.8.0.md
      - 5.8.0 to 5.9.0: identity-server/migration-docs/what-has-changed/what-has-changes-5.8.0 to 5.9.0.md
      - 5.9.0 to 5.10.0: identity-server/migration-docs/what-has-changed/what-has-changes-5.9.0 to 5.10.0.md
      - 5.10.0 to 5.11.0: identity-server/migration-docs/what-has-changed/what-has-changes-5.10.0 to 5.11.0.md
      - 5.11.0 to 6.0.0: identity-server/migration-docs/what-has-changed/what-has-changes-5.11.0 to 6.0.0.md
      - 6.0.0 to 6.1.0: identity-server/migration-docs/what-has-changed/what-has-changes-6.0.0 to 6.1.0.md
      - 6.1.0 to 7.0.0: identity-server/migration-docs/what-has-changed/what-has-changes-6.1.0 to 7.0.0.md

    - is-6.1.0:
      - Migration process:

        - prepare-for-migration: identity-server/migration-docs/is-6.1.0/prepare-for-migration.md
        - migration-process: identity-server/migration-docs/is-6.1.0/migration-process.md
        
      - Migration Doc:  
        - migration 7.0.0: identity-server/migration-docs/is-6.1.0/migrate-to-610.md

    - is-7.0.0:
      - Migration process:
        # - migrating-to-log4j2: identity-server/migration-docs/is-7.0.0/migrating-to-log4j2.md
        - prepare-for-migration: identity-server/migration-docs/is-7.0.0/prepare-for-migration.md
        - migration-process: identity-server/migration-docs/is-7.0.0/migration-process.md
       
      - Migration Doc:  
        - migration 7.0.0: identity-server/migration-docs/is-7.0.0/migrate-to-700.md
      - Other Doc: 
        - migrating-configurations: identity-server/migration-docs/is-7.0.0/migrating-configurations.md
        - migrating-customizations: identity-server/migration-docs/is-7.0.0/migrating-customizations.md
        - migrating-authorization-model: identity-server/migration-docs/is-7.0.0/migrating-authorization-model.md
        - migrating-saas-applications: identity-server/migration-docs/is-7.0.0/migrating-saas-applications.md
        - migrating-roles-related-adaptive-script-functions: identity-server/migration-docs/is-7.0.0/migrating-roles-related-adaptive-script-functions.md
        - migrating-applications-for-tenanted-qualified-urls: identity-server/migration-docs/is-7.0.0/migrating-applications-for-tenanted-qualified-urls.md

        
        
not_in_nav: |
  /page-not-found.md
  /get-started/explore-asgardeo.md
  /get-started/start-integrating-apps.md
  /get-started/try-samples/index.md
  /get-started/try-your-own-app/index.md
  /get-started/try-your-own-app/angular.md
