spring.web.resources.static-locations=classpath:/site/,classpath:/site/test/



# Spring Security OAuth2 Client Configuration
spring.security.oauth2.client.registration.asgardeo.client-id=GVXtEfXZS0fLGC6_6b3l0uFjfIAa
spring.security.oauth2.client.registration.asgardeo.client-secret=GVXtEfXZS0fLGC6_6b3l0uFjfIAa
spring.security.oauth2.client.registration.asgardeo.client-name=Asgardeo
spring.security.oauth2.client.registration.asgardeo.redirect-uri={baseUrl}/login/oauth2/code/asgardeo
spring.security.oauth2.client.registration.asgardeo.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.asgardeo.scope=openid,profile,email

spring.security.oauth2.client.provider.asgardeo.authorization-uri=https://api.asgardeo.io/t/org5tvkj/oauth2/authorize
spring.security.oauth2.client.provider.asgardeo.token-uri=https://api.asgardeo.io/t/org5tvkj/oauth2/token
spring.security.oauth2.client.provider.asgardeo.user-info-uri=https://api.asgardeo.io/t/org5tvkj/oauth2/userinfo
spring.security.oauth2.client.provider.asgardeo.jwk-set-uri=https://api.asgardeo.io/t/org5tvkj/oauth2/jwks
spring.security.oauth2.client.provider.asgardeo.user-name-attribute=sub

# Redirect URI that should match the registered redirect URI in Asgardeo
spring.security.oauth2.client.redirect-uri-template=https://a7ff389d-6e30-4706-ad9c-c246252bc294.e1-us-east-azure.choreoapps.dev/login/oauth2/code/asgardeo

